"""Monte Carlo of Swiss tournaments with a strategic last round.

Everything produced here is SYNTHETIC: it is generated by the model itself
and cannot test the theory.  It illustrates the mechanism, checks the
empirical design (what the analysis recovers when the model is true) and
supplies the pipeline to run on real data.

Usage:  python3 simulate.py [--tournaments 2000] [--seed 20261006]
"""
from __future__ import annotations

import argparse
import csv
import random
from pathlib import Path

import numpy as np

from model import (ACTION_NAME, F, S, Params, case_of, rho,
                   select_equilibrium)

N_PLAYERS = 60            # even, so no byes
N_ROUNDS = 9
TARGETS = (5.5, 6.0, 6.5, 7.0)   # personal score targets (norm / prize band)
P_AFFILIATION = 0.15      # share of pairings between affiliated players


def elo_win_share(e1: float, e2: float) -> float:
    """P(player 1 wins | game decisive), simplified from the Elo curve."""
    return 1.0 / (1.0 + 10 ** (-(e1 - e2) / 400.0))


def swiss_pairs(order: list[int], played: list[set]) -> list[tuple[int, int]]:
    """Greedy Swiss pairing: walk the ranking, avoid repeated opponents."""
    pool = list(order)
    pairs = []
    while pool:
        a = pool.pop(0)
        for k, b in enumerate(pool):
            if b not in played[a]:
                pairs.append((a, b))
                pool.pop(k)
                break
        else:                       # extremely rare: forced repeat
            pairs.append((a, pool.pop(0)))
    return pairs


def run_tournament(tid: int, rng: random.Random, p: Params, d_early: float,
                   rows: list[dict]) -> None:
    elo = [min(2700, max(1600, rng.gauss(2150, 180))) for _ in range(N_PLAYERS)]
    target = [rng.choice(TARGETS) for _ in range(N_PLAYERS)]
    score = [0.0] * N_PLAYERS
    played = [set() for _ in range(N_PLAYERS)]

    for rnd in range(1, N_ROUNDS + 1):
        order = sorted(range(N_PLAYERS), key=lambda i: (-score[i], -elo[i], i))
        for a, b in swiss_pairs(order, played):
            if rng.random() < 0.5:
                a, b = b, a                      # random colours / labels
            q = elo_win_share(elo[a], elo[b])
            played[a].add(b)
            played[b].add(a)

            if rnd < N_ROUNDS:                   # early rounds: normal play
                if rng.random() < d_early:
                    score[a] += 0.5
                    score[b] += 0.5
                elif rng.random() < q:
                    score[a] += 1.0
                else:
                    score[b] += 1.0
                continue

            # ---- last round: players respond to their thresholds ----------
            r1, r2 = target[a] - score[a], target[b] - score[b]
            c1, c2 = case_of(r1), case_of(r2)
            affiliated = rng.random() < P_AFFILIATION
            (a1, a2), n_ne = select_equilibrium(c1, c2, q, p, affiliated)
            d = p.D(a1, a2)
            u = rng.random()
            if u < 1 - d:
                result = 0.5
            else:
                result = 1.0 if rng.random() < q else 0.0
            rho1, rho2 = rho(c1, p), rho(c2, p)
            rows.append({
                "tournament": tid,
                "s1": score[a], "s2": score[b],
                "elo1": round(elo[a]), "elo2": round(elo[b]),
                "target1": target[a], "target2": target[b],
                "r1": r1, "r2": r2, "case1": c1, "case2": c2,
                "rho1": round(rho1, 6), "rho2": round(rho2, 6),
                "rho_sum": round(rho1 + rho2, 6),
                "q": round(q, 6), "affiliated": int(affiliated),
                "action1": ACTION_NAME[a1], "action2": ACTION_NAME[a2],
                "n_equilibria": n_ne, "p_draw": round(1 - d, 6),
                "result1": result, "draw": int(result == 0.5),
            })


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tournaments", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=20261006)
    ap.add_argument("--out", default="data/final_round_pairings.csv")
    args = ap.parse_args()

    p = Params()
    rng = random.Random(args.seed)
    rows: list[dict] = []
    for tid in range(args.tournaments):
        run_tournament(tid, rng, p, d_early=1 - p.D_FF, rows=rows)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {len(rows):,} final-round pairings to {out}")
    print("parameters:", p)


if __name__ == "__main__":
    main()
